# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa16ff8d2bc0fcbf9b657f42293e4caf68b5028e51fb8a1389047c2b8091d160e0b00f29a5896b9b1d777a5331667c0487cdfee410f630050c4d4e8211331e39

test:
  secret_key_base: 8c666dba666ae1811390ddc30a4490a184feed4fe7ecb561ffc05c26f5241028833576335bf0f1b747546481cc372c48eecfbc3920ee4e081c5b9899f4661249

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
